/**
 * `atlas citations report` — what needs human attention. Bank B6 of
 * `task:0021`, and the point of the whole citation pipeline: the edition-2
 * authors asked for a bibliography, but what helps them *while writing* is an
 * answer to "which of my citations are broken, unresolved, or malformed".
 *
 * The report is a durable artifact, not log output. `audit:0010` F2 found that
 * this repo's existing warn-and-continue posture already ships 404s to
 * production, because warnings scroll past in a build log and nobody reads
 * them. Printing a count to stdout is exactly that failure; writing the file
 * and naming it in one line is the fix (`task:0021` D4's implementation
 * obligation). The wrapper below prints that one line and nothing else.
 *
 * Output is deterministic — no timestamp — so re-running after doc edits
 * produces a diff of what changed, not a whole-file rewrite.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Chapter } from '../../../src/textbook-loader/index.js';
import type { CitationInstance } from '../../../src/textbook-loader/citations/extract.js';
import { summarizeCitations } from '../../../src/textbook-loader/citations/extract.js';
import { splitAuthorYear } from '../../../src/textbook-loader/citations/author-year.js';
import type { Store } from '../../../src/textbook-loader/citations/store.js';
import { readStore, STORE_PATH } from './extract-cmd.js';
import { loadChaptersFromCache } from './load.js';

/** Where the report artifact is written, relative to the repo root. */
export const REPORT_PATH = join('data', 'citations', 'citation-report.md');

export type ReportCounts = {
  /** Store entries whose only metadata is the anchor text. */
  unresolved: number;
  /** Anchor texts classified as citations that split into no author+year. */
  malformed: number;
  /** Prose-anchored links that might should be citations. */
  contentLinks: number;
  /** Footnote citations with no hyperlink. */
  unlinked: number;
  /** Sources cited with more than one anchor spelling. */
  inconsistent: number;
};

export type CitationReport = { markdown: string; counts: ReportCounts };

/** `ch1.2` plus the footnote number when there is one — enough to find the text in the doc. */
function location(c: CitationInstance): string {
  const where = c.origin === 'footnote' ? `, footnote ${c.footnoteNumber}` : '';
  return `ch${c.chapterNumber}.${c.sectionNumber}${where}`;
}

/** Sorted, deduplicated locations: the same section cited twice is listed once. */
function locations(instances: CitationInstance[]): string {
  const unique = [...new Set(instances.map(location))].sort();
  return unique.map((l) => `\`${l}\``).join(', ') || 'no citation instance found';
}

function heading(lines: string[], title: string, count: number, explanation: string): void {
  lines.push(`## ${title} (${count})`);
  lines.push('');
  lines.push(explanation);
  lines.push('');
}

/**
 * Build the report. Pure: chapters and store in, Markdown string out.
 *
 * Sections with zero findings are omitted entirely — an author scanning the
 * file should meet only the sections that need them, and a count of zero in a
 * heading is noise that trains people to stop reading headings.
 */
export function buildCitationReport(chapters: Chapter[], store: Store): CitationReport {
  const summary = summarizeCitations(chapters.flatMap((c) => c.sections));
  const citations = summary.instances.filter((i) => i.kind === 'citation');

  // Anchor spellings per canonical URL, so inconsistent citation text is
  // visible without comparing URLs by hand.
  const anchorsByKey = new Map<string, Set<string>>();
  const instancesByKey = new Map<string, CitationInstance[]>();
  for (const c of citations) {
    if (!c.key) continue;
    const anchors = anchorsByKey.get(c.key) ?? new Set<string>();
    const trimmed = c.anchorText.trim();
    if (trimmed) anchors.add(trimmed);
    anchorsByKey.set(c.key, anchors);
    const list = instancesByKey.get(c.key) ?? [];
    list.push(c);
    instancesByKey.set(c.key, list);
  }

  const malformed = citations.filter((c) => splitAuthorYear(c.anchorText) === null);
  const contentLinks = summary.instances.filter((i) => i.kind === 'content-link');
  const unlinked = summary.instances.filter((i) => i.kind === 'unlinked');
  const inconsistent = [...anchorsByKey.entries()].filter(([, a]) => a.size > 1);

  const unresolvedKeys = Object.keys(store)
    .filter((k) => store[k].resolvedBy === 'anchor')
    .sort();

  const lines: string[] = [];
  lines.push('# Citation report — citations needing human attention');
  lines.push('');
  lines.push(
    'Generated by `atlas citations report` from the Google Docs source and the citation store.',
  );
  lines.push(
    'Re-run after editing the documents; nothing here is hand-maintained, so it cannot drift.',
  );
  lines.push('');

  // Zero-finding sections are omitted entirely, not printed with a count of
  // zero: a heading that is always there trains authors to stop reading
  // headings, and an absent section says "nothing here" more honestly.
  if (unresolvedKeys.length > 0) {
    heading(
      lines,
      'Unresolved entries',
      unresolvedKeys.length,
      'Only the anchor text is known for these — no metadata has been resolved and nothing ' +
        'beyond author/year can be rendered. `atlas citations resolve` fills them from arXiv, ' +
        'Crossref and page metadata; hand edits to this store file are also preserved.',
    );
    for (const key of unresolvedKeys) {
      const anchors = [...store[key].anchors].map((a) => `\`${a}\``).join(' / ');
      lines.push(`- ${anchors || '(no anchor text)'} — ${locations(instancesByKey.get(key) ?? [])} — ${key}`);
    }
    lines.push('');
  }

  if (malformed.length > 0) {
    heading(
      lines,
      'Malformed anchor text',
      malformed.length,
      'These look like citations but could not be split into an author and a year, so no ' +
        'bibliography entry can name them. Fix the link text in the Google Doc — the corpus ' +
        'shows real cases: `Burns et. al. 2023` (missing comma), a stray closing paren.',
    );
    for (const c of malformed) {
      lines.push(`- \`${location(c)}\` — \`${c.anchorText.trim()}\` (${c.key ?? c.rawUrl ?? 'no URL'})`);
    }
    lines.push('');
  }

  if (contentLinks.length > 0) {
    heading(
      lines,
      'Content links — prose anchors that might be citations',
      contentLinks.length,
      'Hyperlinks whose text is prose ("available here") rather than an author and year. Many ' +
        'are ordinary links; anything that *should* be cited needs its link text changed to ' +
        '"Author, Year" form in the Google Doc.',
    );
    for (const c of contentLinks) {
      lines.push(`- \`${location(c)}\` — \`${c.anchorText.trim()}\` (${c.key ?? c.rawUrl ?? 'no URL'})`);
    }
    lines.push('');
  }

  if (unlinked.length > 0) {
    heading(
      lines,
      'Unlinked footnote citations',
      unlinked.length,
      'Author-year text in a footnote with no hyperlink, so there is no URL to key an entry ' +
        'on. The corpus currently has none — this section exists so the first one an author ' +
        'writes is reported rather than silently dropped.',
    );
    for (const c of unlinked) {
      lines.push(`- \`${location(c)}\` — \`${c.anchorText.trim()}\``);
    }
    lines.push('');
  }

  if (inconsistent.length > 0) {
    heading(
      lines,
      'Inconsistent citation spelling',
      inconsistent.length,
      'One source cited with more than one anchor spelling. Rendering collapses these to one ' +
        'entry, but the inconsistent input is worth fixing at the source while it is cheap.',
    );
    for (const [key, anchors] of inconsistent) {
      const spellings = [...anchors].sort().map((a) => `\`${a}\``).join(' / ');
      lines.push(`- ${spellings} — ${locations(instancesByKey.get(key) ?? [])} — ${key}`);
    }
    lines.push('');
  }

  const counts: ReportCounts = {
    unresolved: unresolvedKeys.length,
    malformed: malformed.length,
    contentLinks: contentLinks.length,
    unlinked: unlinked.length,
    inconsistent: inconsistent.length,
  };
  return { markdown: lines.join('\n'), counts };
}

/**
 * Run the command: write the artifact, print one line naming it.
 *
 * The store is required because "unresolved" is a property of the store, not
 * the documents. An empty store is legitimate (nothing resolved yet); a
 * missing one almost certainly means extract has not run.
 */
export async function citationsReport(root: string, outPath?: string): Promise<number> {
  if (!existsSync(join(root, STORE_PATH))) {
    console.error(`no citation store at ${STORE_PATH} — run \`atlas citations extract\` first`);
    return 1;
  }
  const store = readStore(root);
  const chapters = await loadChaptersFromCache();
  const report = buildCitationReport(chapters, store);

  const dest = outPath ?? join(root, REPORT_PATH);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, report.markdown, 'utf8');

  console.log(
    `${report.counts.unresolved} unresolved · ${report.counts.malformed} malformed · ` +
      `${report.counts.contentLinks} content links · ${report.counts.unlinked} unlinked · ` +
      `${report.counts.inconsistent} inconsistent spellings — wrote ${dest}`,
  );
  return 0;
}