/**
 * `atlas citations urls` — every cited source, per chapter and section, as
 * copy-pasteable Markdown.
 *
 * This is the deliberately crude slice of `task:0026`, shipped ahead of the CSL
 * export because it is immediately useful: the edition-2 authors can paste the
 * result into a Google Doc and start working from it today, without waiting for
 * metadata resolution (`task:0027`) or any rendering (phase 2).
 *
 * It is NOT the bibliography. Titles here are the citation's anchor text, not
 * resolved titles, so "Chollet, 2019" appears rather than "On the Measure of
 * Intelligence". That is the honest limit of what is knowable with no network
 * call, and the file says so at the top so nobody mistakes it for the finished
 * artifact.
 *
 * Output is deterministic — no timestamp — so regenerating it produces a clean
 * diff rather than a whole-file change.
 */
import type { Chapter } from '../../../src/textbook-loader/index.js';
import {
  extractSectionCitations,
  type CitationInstance,
} from '../../../src/textbook-loader/citations/extract.js';

export type UrlReport = {
  markdown: string;
  totalCitations: number;
  uniqueSources: number;
  unrecognised: number;
};

function bullet(c: CitationInstance): string {
  const label = c.anchorText.trim() || c.key || '(no link text)';
  const where = c.origin === 'footnote' ? ` [footnote ${c.footnoteNumber}]` : '';
  return `- ${label}${where} (${c.key ?? 'no URL'})`;
}

/**
 * Build the Markdown report. Pure: chapters in, string out, no I/O.
 *
 * Sections with no citations are still listed, with an explicit "none" line.
 * An author scanning for gaps needs to tell "this section cites nothing" apart
 * from "this section is missing from the report".
 */
export function formatUrlMarkdown(chapters: Chapter[]): UrlReport {
  const lines: string[] = [];
  const allCitations: CitationInstance[] = [];
  const unrecognised: CitationInstance[] = [];

  lines.push('# AI Safety Atlas — cited sources by chapter and section');
  lines.push('');
  lines.push(
    'Generated by `atlas citations urls` directly from the Google Docs source. **This is an',
  );
  lines.push(
    'interim list, not the finished bibliography.** Each entry shows the citation as it is',
  );
  lines.push(
    'written in the text (author and year) followed by the URL it links to — titles have not',
  );
  lines.push('been looked up yet.');
  lines.push('');
  lines.push(
    'Nothing here is hand-maintained: it is read out of the documents, so it cannot drift from',
  );
  lines.push('the prose. Re-run the command after editing and it updates.');
  lines.push('');

  for (const chapter of chapters) {
    const chapterCitations: CitationInstance[] = [];
    const body: string[] = [];

    for (const section of chapter.sections) {
      const found = extractSectionCitations(section);
      const cites = found.filter((c) => c.kind === 'citation' || c.kind === 'unlinked');
      unrecognised.push(...found.filter((c) => c.kind === 'content-link'));
      chapterCitations.push(...cites);

      body.push(`### ${chapter.number}.${section.number} ${section.title}`);
      body.push('');
      if (cites.length === 0) {
        body.push('_No citations in this section._');
      } else {
        for (const c of cites) body.push(bullet(c));
      }
      body.push('');
    }

    allCitations.push(...chapterCitations);
    const unique = new Set(chapterCitations.map((c) => c.key).filter(Boolean)).size;
    lines.push(`## Chapter ${chapter.number} — ${chapter.title}`);
    lines.push('');
    lines.push(`_${chapterCitations.length} citations · ${unique} unique sources._`);
    lines.push('');
    lines.push(...body);
  }

  // A deduplicated master list. The per-section view answers "what does this
  // section cite"; this one answers "what does the book cite", which is the
  // question a bibliography actually exists to answer.
  const byKey = new Map<string, string[]>();
  for (const c of allCitations) {
    if (!c.key) continue;
    const labels = byKey.get(c.key) ?? [];
    const label = c.anchorText.trim();
    if (label && !labels.includes(label)) labels.push(label);
    byKey.set(c.key, labels);
  }
  const keys = [...byKey.keys()].sort();

  lines.push('---');
  lines.push('');
  lines.push(`## All unique sources (${keys.length})`);
  lines.push('');
  lines.push('Deduplicated across the whole book. Where one source is cited with more than one');
  lines.push('spelling, every spelling seen is shown — useful for spotting inconsistencies.');
  lines.push('');
  for (const key of keys) {
    lines.push(`- ${byKey.get(key)!.join(' / ') || '(no link text)'} (${key})`);
  }
  lines.push('');

  if (unrecognised.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`## Links not recognised as citations (${unrecognised.length})`);
    lines.push('');
    lines.push('These are hyperlinks whose text is prose rather than an author and year, so they');
    lines.push(
      'were treated as ordinary links. **Worth a glance** — anything here that should be a',
    );
    lines.push('citation needs its link text changed in the Google Doc to "Author, Year" form.');
    lines.push('');
    for (const c of unrecognised) {
      lines.push(
        `- ch${c.chapterNumber}.${c.sectionNumber} — "${c.anchorText.trim()}" (${c.key ?? c.rawUrl})`,
      );
    }
    lines.push('');
  }

  return {
    markdown: lines.join('\n'),
    totalCitations: allCitations.length,
    uniqueSources: keys.length,
    unrecognised: unrecognised.length,
  };
}
