"""``atlas citations propose`` - gather evidence for the entries a human must finish.

``task:0032`` AC-5. The last few dozen sources in this corpus cannot be resolved
automatically, and ``task:0032`` D2 and D3 record the two attempts that were
measured and rejected for trying: PDF title extraction (0 of 12 PDFs carried a
``/Title``; a largest-font heuristic came out clean about 5 times in 16) and a
Crossref title search (which returned a *different* paper, ranked first, at a
score indistinguishable from a correct hit's).

The conclusion those measurements point to is not "try harder". It is that the
tool should stop at the boundary of what it can know and hand over everything it
gathered. A 70%-correct title is worse than no title, because nothing downstream
can tell which 70% - but the first lines of a PDF's first page are *excellent*
evidence for a person who can read them in a second.

So this command resolves nothing. It writes a starting point: one stub per
unresolved entry, commented out, carrying the anchor text the authors wrote, the
sections citing it, why the last attempt failed, and whatever the page or
document says about itself. The human uncomments, corrects, and moves it into
``overrides.yaml``.

This is the same separation ``report`` already draws between detecting duplicates
and merging them: **propose, never decide.**
"""

from __future__ import annotations

import io
import re
from pathlib import Path

from ..overrides import OVERRIDES_PATH
from ..resolvers import make_context
from ..resolvers._http import MAX_HTML_BYTES, get_text_capped
from ..resolvers.base import Unreachable
from ..resolvers.opengraph import _soup, meta_content, title_tag
from ..resolvers.wayback import snapshot_for
from ..scan import Citation, ScanError, read_scan
from ..store import Store
from .extract import STORE_PATH, read_store
from .report import UNREACHABLE_REASONS
from .resolve import DEFAULT_INTERVAL_S, USER_AGENT

#: Gitignored: a worklist, not an artifact. What survives review moves by hand
#: into ``overrides.yaml``, which is the committed file.
PROPOSALS_PATH = Path("data") / "citations" / "overrides.proposed.yaml"

#: The order groups appear in the worklist, and it is the order the work batches
#: in: what a library login fixes, then what a dead link needs decided, then the
#: PDFs and client-rendered pages that just need opening.
REASON_ORDER = {"refused": 0, "gone": 1, "unavailable": 2}

#: What each group needs from a person, said in those terms rather than in HTTP.
GROUP_TITLES = {
    "refused": "BEHIND A PAYWALL OR BOT CHECK - needs whatever access you have",
    "gone": "THE PAGE IS GONE - decide what to cite instead, or cite the archive",
    "unavailable": "THE SITE WOULD NOT ANSWER - worth retrying before filling in by hand",
    "": "NO METADATA TO READ - a PDF, or a page that renders client-side",
}

#: Enough of a PDF's first page to contain a title and a byline, not so much that
#: the file becomes unreadable. Measured against the corpus: every title that was
#: recoverable at all sat in the first three non-empty lines.
PDF_HEAD_LINES = 6

#: Fetching a PDF to read one page is the most expensive thing here.
PDF_TIMEOUT_S = 30.0

#: The largest PDF this corpus cites is 28 MB (OpenAI's DALL-E 3 paper), so the
#: bound is set above it rather than at a round number that would exclude it.
#: One file at a time, on a machine where `pnpm verify` costs far more.
MAX_PDF_BYTES = 32 * 1024 * 1024

HEADER = f"""# Proposed overrides - evidence gathered, nothing decided.
#
# Generated by `atlas citations propose`. NOT an artifact and NOT committed:
# this is a worklist. Read each block, correct it, and move what is right into
# {OVERRIDES_PATH.as_posix()}, which is the reviewed file the pipeline reads.
#
# Everything below is commented out on purpose. These are not answers - they are
# what could be gathered about sources no API describes. A PDF's first lines
# usually contain its title; sometimes they contain a copyright notice instead.
# You are the check on that, which is the whole point (task:0032 D2).
"""


def _evidence_for_pdf(body: bytes) -> list[str]:
    """The first few non-empty lines of a PDF's first page.

    Deliberately raw and unranked. An earlier version ranked lines by font size
    and returned the largest; it read "The American Enterprise Institute (AEI) is
    a nonpartisan, nonprofit, 501(c)(3) educational organization" as the title of
    a real corpus entry, because a report set in one size has no largest font.
    Showing six lines to a person costs nothing and cannot be wrong in that way.
    """
    try:
        from pypdf import PdfReader
    except ImportError:  # pragma: no cover - dependency is declared
        return ["(pypdf is not installed)"]
    try:
        reader = PdfReader(io.BytesIO(body))
        text = reader.pages[0].extract_text() or ""
    except Exception as exc:
        return [f"(could not read the PDF: {type(exc).__name__})"]
    lines = [re.sub(r"\s+", " ", line).strip() for line in text.splitlines()]
    return [line for line in lines if line][:PDF_HEAD_LINES]


def _evidence_for_html(html: str) -> list[str]:
    """What an HTML page says about itself, even when it is not enough to resolve on."""
    soup = _soup(html)
    found = []
    for label, key in (("og:title", "og:title"), ("citation_title", "citation_title")):
        value = meta_content(soup, key)
        if value:
            found.append(f"{label}: {value}")
    tag = title_tag(soup)
    if tag:
        found.append(f"<title>: {tag}")
    site = meta_content(soup, "og:site_name")
    if site:
        found.append(f"og:site_name: {site}")
    return found


def gather_evidence(url: str, ctx) -> list[str]:
    """Fetch the source and report what it says about itself. Never decides."""
    body = get_text_capped(ctx, url, cap=MAX_HTML_BYTES, timeout=PDF_TIMEOUT_S, html_only=True)
    if isinstance(body, Unreachable):
        found = [f"(fetch failed: {UNREACHABLE_REASONS.get(body.reason, body.reason)})"]
        # The most useful thing we can hand someone who has to open this by hand
        # is a link that actually opens. A paywall or a dead address often has a
        # readable copy in the archive even when the resolver could not use it -
        # a PDF snapshot, typically, which is exactly what the resolver declines.
        snapshot = snapshot_for(url, ctx)
        if isinstance(snapshot, tuple):
            found.append(f"archived copy: {snapshot[0]}")
        return found
    if body:
        return _evidence_for_html(body) or ["(the page carries no title metadata)"]

    # Not HTML. Almost always a PDF in this corpus, and the one case where the
    # document itself is the only description of it that exists.
    ctx.throttle()
    try:
        response = ctx.client.get(url, timeout=PDF_TIMEOUT_S, follow_redirects=True)
        content = response.content
    except Exception as exc:
        return [f"(fetch failed: {type(exc).__name__})"]
    if not content.startswith(b"%PDF"):
        return ["(not HTML and not a PDF)"]
    # Never parse a truncated PDF. A PDF's cross-reference table lives at the
    # *end* of the file, so a body cut at a byte cap is not a smaller document,
    # it is a broken one - and the parser either raises (which is the lucky
    # outcome) or returns nonsense. Found on the 28 MB DALL-E 3 paper, which an
    # 8 MB cap turned into a PdfStreamError.
    if len(content) > MAX_PDF_BYTES:
        return [f"(PDF is {len(content) / 1e6:.0f} MB - too large to read here; open it by hand)"]
    return _evidence_for_pdf(content)


def _stub(key: str, store: Store, instances: list[Citation], evidence: list[str]) -> list[str]:
    """One commented-out override block, with its evidence above it."""
    entry = store[key]
    anchors = entry.get("anchors") or []
    reason = UNREACHABLE_REASONS.get(str(entry.get("unreachable", "")))
    where = sorted({c.location for c in instances})

    lines = ["", f"# ---- {key}"]
    if anchors:
        lines.append(f"#   cited as: {' / '.join(anchors)}")
    if where:
        lines.append(f"#   cited in: {', '.join(where)}")
    if reason:
        lines.append(f"#   last attempt: {reason}")
    for item in evidence:
        lines.append(f"#   evidence: {item}")
    lines += [
        f"# {key}:",
        "#   title:",
        "#   author:",
        "#     - literal:",
        "#   issued: { date-parts: [[]] }",
        "#   type:",
        "#   container-title:",
    ]
    return lines


def citations_propose(root: Path, limit: int | None = None, interval_s: float | None = None) -> int:
    """Write the worklist. Networked, like ``resolve``, and just as interruptible."""
    if not (root / STORE_PATH).exists():
        print(f"atlas: no store at {STORE_PATH} - run `atlas citations extract` first")
        return 1
    try:
        scan = read_scan(root)
    except ScanError as exc:
        print(f"atlas: {exc}")
        return 1

    store = read_store(root)
    instances_by_key: dict[str, list[Citation]] = {}
    for citation in scan.all_citations():
        if citation.key:
            instances_by_key.setdefault(citation.key, []).append(citation)

    # Grouped by *why* each one is here, because the work batches that way: the
    # paywalled ones need whatever library access the reader has, the PDFs need
    # opening and skimming, the dead ones need a decision about what to cite
    # instead. Sorted within a group so the file diffs cleanly between runs.
    def group(key: str) -> tuple[int, str]:
        reason = str(store[key].get("unreachable", ""))
        return (REASON_ORDER.get(reason, len(REASON_ORDER)), key)

    pending = sorted((k for k, e in store.items() if e.get("resolvedBy") == "anchor"), key=group)
    if not pending:
        print("Nothing to propose: every entry carries resolved or reviewed metadata.")
        return 0
    targets = pending[:limit] if limit else pending

    ctx = make_context(
        DEFAULT_INTERVAL_S if interval_s is None else interval_s,
        USER_AGENT,
    )
    print(f"Gathering evidence for {len(targets)} unresolved of {len(pending)}.")

    lines = [HEADER.rstrip()]
    seen_group: str | None = None
    try:
        for index, key in enumerate(targets, 1):
            reason = str(store[key].get("unreachable", ""))
            if reason != seen_group:
                seen_group = reason
                lines += ["", f"# ===== {GROUP_TITLES.get(reason, GROUP_TITLES[''])}"]
            lines += _stub(key, store, instances_by_key.get(key, []), gather_evidence(key, ctx))
            if index % 25 == 0:
                print(f"  {index}/{len(targets)}")
    except KeyboardInterrupt:
        # Same posture as resolve: keep what was gathered rather than discarding
        # an interrupted run's work.
        print("\nStopped; writing what was gathered so far.")
    finally:
        ctx.client.close()

    dest = root / PROPOSALS_PATH
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {dest} - review it, then move what is right into {OVERRIDES_PATH}.")
    return 0
