"""Reviewed identity decisions: several URLs, one work. ``task:0031``.

Canonicalization (``canonical-url.ts``) merges two URLs only when they are the
same document *by construction* - an arXiv ``/abs`` and ``/pdf``, a DOI resolver
prefix. That is deliberately conservative, because over-merging silently loses a
citation while under-merging leaves a visible duplicate somebody can fix.

It leaves a real gap. A DeepMind post lives at ``deepmind.com`` and
``deepmind.google``; an Alignment Forum post is cross-posted to LessWrong under
the same id; a paper on arXiv is also a PDF on the publisher's CDN. Nothing in
the addresses says so. ``task:0021`` edge case 2 named the answer at the time:
**a manual alias file**.

This is that file's reader. Two sections, because the report has two failure
modes and only one of them is a merge:

``aliases``
    ``survivor: [other URLs]``. Every listed URL folds onto the survivor, which
    keeps its own metadata. The alias addresses are recorded on the surviving
    entry as ``sameAs`` so the alternative address is not lost - a reader who
    followed the Doc's link should still find it named in the bibliography.

``not-duplicates``
    Groups the detector flags that a human has checked and rejected. Without
    this the duplicates section of the report is a standing complaint rather
    than a worklist (``task:0031`` AC-4), and the same four false positives get
    re-investigated by every person who reads it. Four are known: two LessWrong
    comments on one shortform thread are two comments by two people; an AI
    textbook and an Our World in Data explainer share the title "Artificial
    Intelligence"; a Dafoe book chapter and a GovAI paper collide only because
    the fingerprint strips subtitles; two OpenReview papers share a scraped
    "Verifying your browser" title that is not a title at all.

**Never automatic.** Detection is a heuristic over a title fingerprint; identity
is not. The report proposes, this file decides, and nothing merges that a person
has not written down here.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from .store import Store, _plain

#: Reviewed input, committed, hand-edited. Not generated by any command.
ALIASES_PATH = Path("data") / "citations" / "aliases.yaml"

#: The mapping section: surviving URL -> the URLs that fold onto it.
ALIASES_KEY = "aliases"

#: The suppression section: a list of URL groups checked and found distinct.
NOT_DUPLICATES_KEY = "not-duplicates"

FILE_HEADER = """# Citation identity decisions - hand-written, never generated.
#
# Canonicalization merges two URLs only when they are the same document by
# construction. Everything else needs a person to say so. See task:0031.
#
# aliases: the key is the entry to KEEP; the list folds onto it. The surviving
# entry keeps its own metadata and records the others as `sameAs`.
#
#   https://deepmind.google/discover/blog/specification-gaming:
#     - https://deepmind.com/blog/specification-gaming
#
# not-duplicates: groups `atlas citations report` flags that are NOT the same
# work. Listing one here stops the report repeating it, so the duplicates
# section stays a worklist instead of a standing complaint.
#
#   - - https://example.org/a
#     - https://example.org/b
"""


def _yaml() -> YAML:
    y = YAML()
    y.width = 100
    y.indent(mapping=2, sequence=2, offset=0)
    y.preserve_quotes = True
    return y


class Aliases:
    """The parsed file, in the two shapes its callers actually need."""

    def __init__(
        self,
        groups: dict[str, list[str]] | None = None,
        not_duplicates: list[list[str]] | None = None,
    ) -> None:
        #: Surviving URL -> the URLs folding onto it, as written.
        self.groups = groups or {}
        #: Groups a human has checked and rejected, as written.
        self.not_duplicates = not_duplicates or []
        #: Alias URL -> surviving URL. The lookup every caller wants.
        self.of: dict[str, str] = {
            alias: survivor for survivor, aliases in self.groups.items() for alias in aliases
        }

    def resolve(self, url: str | None) -> str | None:
        """The surviving URL for an address, or the address unchanged.

        Single-step by design: an alias whose survivor is itself an alias is a
        chain nobody wrote down on purpose, and following it would make the
        file's effect depend on its own ordering. :func:`chains` reports them so
        they get fixed in the file instead.
        """
        if url is None:
            return None
        return self.of.get(url, url)

    def chains(self) -> list[tuple[str, str]]:
        """``(alias, survivor)`` pairs whose survivor is itself aliased away."""
        return sorted((a, s) for a, s in self.of.items() if s in self.of)

    def suppressed(self) -> list[frozenset[str]]:
        """The rejected groups, as unordered sets, for the report to skip."""
        return [frozenset(group) for group in self.not_duplicates if len(group) > 1]

    def rejects(self, group: list[str]) -> bool:
        """True when a reviewer has already found this group to be distinct works.

        Matched by **subset**, not equality. "These four comments on one thread
        are four different comments" is a statement about the four URLs, and it
        stays true of any pair among them - but the detector's grouping shifts
        as metadata improves, so an equality test would silently stop
        suppressing the moment one entry gained an author.
        """
        candidate = frozenset(group)
        return any(candidate <= rejected for rejected in self.suppressed())


def parse_aliases(text: str) -> Aliases:
    """Parse the alias file. An empty or comment-only file aliases nothing."""
    parsed = _yaml().load(text)
    if not isinstance(parsed, dict):
        return Aliases()
    plain = _plain(parsed)

    groups: dict[str, list[str]] = {}
    for survivor, aliases in (plain.get(ALIASES_KEY) or {}).items():
        if not isinstance(aliases, list):
            continue
        # A URL cannot be its own alias, and a stub with an empty list is
        # someone's half-finished thought rather than an instruction.
        listed = sorted({a for a in aliases if isinstance(a, str) and a and a != survivor})
        if listed:
            groups[str(survivor)] = listed

    not_duplicates = [
        sorted({u for u in group if isinstance(u, str) and u})
        for group in (plain.get(NOT_DUPLICATES_KEY) or [])
        if isinstance(group, list)
    ]
    return Aliases(groups, [g for g in not_duplicates if len(g) > 1])


def read_aliases(root: Path) -> Aliases:
    """Read the alias file from a checkout root; an absent file aliases nothing."""
    path = root / ALIASES_PATH
    if not path.exists():
        return Aliases()
    return parse_aliases(path.read_text(encoding="utf-8"))


def serialize_aliases(aliases: Aliases) -> str:
    body: dict[str, Any] = {}
    if aliases.groups:
        body[ALIASES_KEY] = {key: aliases.groups[key] for key in sorted(aliases.groups)}
    if aliases.not_duplicates:
        body[NOT_DUPLICATES_KEY] = sorted(aliases.not_duplicates)
    buf = io.StringIO()
    _yaml().dump(body, buf)
    return FILE_HEADER + buf.getvalue()


def fold_aliases(store: Store, aliases: Aliases) -> tuple[Store, list[tuple[str, str]], list[str]]:
    """Collapse aliased entries into their survivors.

    Returns the new store, the ``(removed, survivor)`` pairs, and the survivor
    URLs of groups that name nothing this corpus cites.

    ``task:0031`` D1 is **delete, and name every removal on stdout**. The store
    is 1.2 MB of generated YAML, so a vanished entry is invisible in review; the
    survivor's new ``sameAs`` line is the half of the diff a reviewer can
    actually see, and the printed list is the other half.

    ``task:0031`` D2 is **the survivor keeps its own metadata**. Two resolutions
    of one work disagree - the arXiv record and a publisher's page give the o1
    System Card different types and containers - and a merged entry would be a
    third description that neither source stated. What does transfer is the
    anchor list, because those are spellings a reader will meet in the prose and
    they belong to the work rather than to the address.

    **An unresolved survivor is the exception**, and it has to be. If the prose
    cites only the mirror, ``read_scan`` rewrites that citation onto the
    surviving address and extraction mints a fresh anchor-only entry for it -
    so "keep the survivor's own metadata" would mean keeping "Bostrom, 2014" and
    deleting the record that knew the title. That is the silent citation loss
    this whole file is written to avoid, so a resolved alias hands its
    description to the address being kept. Identity is still the survivor's:
    ``id`` and ``URL`` are rewritten, never inherited (``task:0021`` D1).
    """
    out: Store = dict(store)
    removed: list[tuple[str, str]] = []
    stale: list[str] = []

    for survivor, listed in sorted(aliases.groups.items()):
        present = [alias for alias in listed if alias in out]
        if survivor not in out:
            # Nothing to fold onto. Reported rather than invented: minting an
            # entry here would make the alias file a source of bibliography
            # entries, which is exactly the authority it is not meant to have.
            # An alias with no survivor cannot happen for a live citation -
            # extraction would have created one - so this means the whole group
            # has left the prose.
            if not present:
                stale.append(survivor)
            continue

        entry = out[survivor]
        anchors = set(entry.get("anchors", []))
        for alias in present:
            aliased = out[alias]
            anchors |= set(aliased.get("anchors", []))
            if entry.get("resolvedBy") == "anchor" and aliased.get("resolvedBy") != "anchor":
                item = {**aliased.get("item", {}), "id": survivor, "URL": survivor}
                item.pop("note", None)
                entry = {**aliased, "item": item}
            del out[alias]
            removed.append((alias, survivor))

        # `sameAs` is recorded for every listed address, not only the ones that
        # had an entry: the point is to state where else this work is published,
        # and that is true whether or not the prose happens to cite it today.
        # Entry-level, deliberately outside `item`: CSL has no `sameAs`, and the
        # BibTeX and CSL-JSON exports are the compiled form of `item` alone.
        out[survivor] = {**entry, "anchors": sorted(anchors), "sameAs": listed}

    return out, removed, sorted(set(stale))
