"""Reviewed citation metadata for sources no API describes. ``task:0032`` AC-5.

Some sources cannot be resolved by any amount of engineering, and that is a fact
about the web rather than a gap in this tool. Measured over this corpus: 57 of
the 132 unresolved entries live behind a publisher WAF or a paywall, 29 are PDFs
with an empty metadata dictionary, and a further 11 are pages that no longer
exist at all.

For those, a human reads the page — they cited it, so they have read it once
already — and records what it is. This file is where that judgement lives.

**Why not hand-edit the store instead?** ``task:0032`` D4. ``sources.yaml`` is
1.2 MB of generated YAML, so an entry typed into it by hand is invisible in
review, indistinguishable from resolver output, and gone the first time someone
runs ``--redo``. A separate file keeps human judgement reviewable as a diff and
lets the store stay disposable.

Precedence is **override → resolver → anchor**, and an override is never
overwritten: ``resolve`` skips an entry it owns, and ``--redo`` refuses to target
it. The same posture ``task:0031`` takes for aliases and ``task:0021`` D1 takes
for identity — where a machine cannot know, a human records the answer and the
tool stops guessing.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from .store import CslItem, Store, StoreEntry, _plain

#: Reviewed input, committed, hand-edited. Not generated by any command.
OVERRIDES_PATH = Path("data") / "citations" / "overrides.yaml"

#: What ``resolvedBy`` reads for an entry a human filled in. Deliberately not a
#: resolver name: nothing resolved this, someone decided it.
OVERRIDE_SOURCE = "override"

FILE_HEADER = """# Reviewed citation metadata — hand-written, never generated.
#
# One block per canonical URL, holding CSL fields that override whatever the
# resolvers found (or failed to find). See task:0032 D4.
#
# Use this for sources no API describes: a paywalled paper, a PDF with no
# metadata, a page behind a bot check, a dead link you have found an archived
# copy of. Every field is optional; what you give wins, what you leave out
# falls back to the resolvers.
#
#   https://example.org/some-report.pdf:
#     title: The Title As Printed On The Document
#     author:
#       - literal: Some Institute          # organisation: no given/family split
#       - family: Chollet
#         given: François
#     issued: { date-parts: [[2024, 5]] }  # year, or year and month, or full date
#     type: report                         # see CSL_TYPES in store.py
#     container-title: Journal or Publisher
#     DOI: 10.1000/example
#
# `atlas citations propose` writes a starting point for each unresolved entry,
# with whatever evidence could be gathered, into overrides.proposed.yaml.
"""


def _yaml() -> YAML:
    y = YAML()
    y.width = 100
    y.indent(mapping=2, sequence=2, offset=0)
    y.preserve_quotes = True
    return y


def parse_overrides(text: str) -> dict[str, CslItem]:
    """Parse the overrides file. An empty or comment-only file is no overrides."""
    parsed = _yaml().load(text)
    if not isinstance(parsed, dict):
        return {}
    plain = _plain(parsed)
    # A key with no body is a stub someone has not filled in yet, not an
    # instruction to blank the entry.
    return {k: v for k, v in plain.items() if isinstance(v, dict) and v}


def read_overrides(root: Path) -> dict[str, CslItem]:
    """Read the overrides file if it exists; no overrides otherwise."""
    path = root / OVERRIDES_PATH
    if not path.exists():
        return {}
    return parse_overrides(path.read_text(encoding="utf-8"))


def serialize_overrides(overrides: dict[str, CslItem]) -> str:
    ordered = {key: overrides[key] for key in sorted(overrides)}
    buf = io.StringIO()
    _yaml().dump(ordered, buf)
    return FILE_HEADER + buf.getvalue()


def apply_override(entry: StoreEntry, fields: CslItem) -> StoreEntry:
    """Fold reviewed fields over one entry.

    The entry's ``id`` and ``URL`` are held back from the override, because both
    are its identity (``task:0021`` D1) rather than metadata about the work. An
    override that could rewrite them would let a typo silently detach an entry
    from the citations pointing at it.

    The unresolved ``note`` is dropped, for the same reason ``apply_resolution``
    drops it: it marks an entry as needing work, and this one no longer does.
    """
    item: dict[str, Any] = {**entry.get("item", {}), **fields}
    item["id"] = entry["item"]["id"]
    item["URL"] = entry["item"].get("URL", entry["item"]["id"])
    item.pop("note", None)
    return {
        "item": item,
        "resolvedBy": OVERRIDE_SOURCE,
        "anchors": entry.get("anchors", []),
    }


def apply_overrides(store: Store, overrides: dict[str, CslItem]) -> tuple[Store, list[str]]:
    """Apply every override that matches a store entry.

    Returns the new store and the keys that matched nothing — a URL in the
    overrides file with no entry behind it is almost always a typo or a citation
    that has since been edited out of the prose, and silently ignoring it is how
    a file like this rots.
    """
    out: Store = dict(store)
    unmatched: list[str] = []
    for key, fields in overrides.items():
        if key in out:
            out[key] = apply_override(out[key], fields)
        else:
            unmatched.append(key)
    return out, sorted(unmatched)
