"""The bibliography store: CSL entries, one per source, as editable YAML.

Bank B4 of ``task:0021``, and the irreversible part. ``task:0021`` D1 fixes entry
identity as **one global entry per source, keyed by canonical URL**, with
per-(edition, language, chapter, section) citation instances pointing at it. A
URL does not translate; the prose around it does.

``task:0021`` D2 fixes the schema as **CSL** - the Citation Style Language item
model that Zotero, Pandoc and Crossref already speak. Using it rather than
inventing fields buys style-independent rendering, BibTeX export and Zotero
round-trip for free.

Stored as YAML rather than JSON because these files are hand-edited: roughly 600
of the sources have no API that describes them, so a human will fix them in a
text editor and review them in a diff. YAML takes comments and produces readable
diffs; CSL-JSON is the compiled form.

Ported from ``store.ts`` under ``task:0029``. The CSL model is unchanged - only
what writes it moved. Per ``task:0029`` D4 the emitted bytes differ from the
TypeScript original's (a different YAML emitter wraps and quotes differently);
what is guaranteed, and tested against the real committed store, is that every
entry survives semantically identical.
"""

from __future__ import annotations

import io
import re
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from ruamel.yaml import YAML

#: One stored entry is ``{"item": CslItem, "resolvedBy": str, "anchors": [str]}``.
#: Deliberately plain dicts rather than dataclasses: CSL defines far more fields
#: than this project populates, and a resolver that learns to fill ``volume`` or
#: ``page`` should not need a change here. Narrowing CSL to a closed set would
#: recreate the bespoke schema D2 exists to avoid.
StoreEntry = dict[str, Any]
Store = dict[str, StoreEntry]
CslItem = dict[str, Any]
CslName = dict[str, str]

#: The CSL item types this project emits. ``webpage`` versus ``post-weblog``
#: matters for rendering: a lab announcement is a web page, an Alignment Forum or
#: LessWrong entry is a blog post, and citation styles format them differently.
CSL_TYPES = (
    "article-journal",
    "paper-conference",
    "article",  # preprints, including arXiv
    "webpage",
    "post-weblog",
    "motion_picture",  # video
    "report",
    "document",  # last resort
)

_FILE_HEADER = """# Bibliography entries for the AI Safety Atlas.
#
# Generated by `atlas citations extract` and filled in by
# `atlas citations resolve`. Hand edits are expected and preserved: an entry
# whose `resolvedBy` is anything other than "anchor" is never overwritten by
# re-extraction.
#
# Schema is CSL (Citation Style Language) - see task:0021 D2. The key of each
# entry is its canonical URL, which is the entry's identity (task:0021 D1).
"""

_BLOG_HOST_SUFFIXES = (
    "alignmentforum.org",
    "lesswrong.com",
    "substack.com",
    "effectivealtruism.org",
)


def _yaml() -> YAML:
    """A round-trip YAML handler configured to match the store's conventions.

    Round-trip mode is what preserves mapping order - the safe dumper sorts keys
    alphabetically, which would scramble ``item`` / ``resolvedBy`` / ``anchors``
    and every CSL field inside them into a shape no reviewer would recognise.
    """
    y = YAML()
    y.width = 100
    y.indent(mapping=2, sequence=2, offset=0)
    y.preserve_quotes = True
    return y


def year_to_csl_date(year: str | int) -> dict[str, Any]:
    """A CSL date from a four-digit year, which is all an anchor text ever gives."""
    return {"date-parts": [[int(year)]]}


def literal_name(name: str) -> CslName:
    """A CSL name that makes no claim about name structure.

    ``literal`` is used deliberately and often. An anchor reading "Giattino et
    al." or "Oxford Reference" has no recoverable family/given split, and
    inventing one produces confidently wrong output in every rendered style. CSL
    supports ``literal`` precisely so an honest unparsed name is representable.
    """
    return {"literal": name}


def infer_csl_type(url: str) -> str:
    """The CSL item type implied by a canonical URL.

    A heuristic, and only ever a starting point: a resolver with real metadata
    should overwrite it. It exists so that an unresolved entry still renders as
    something more useful than a generic document.
    """
    try:
        host = (urlsplit(url).hostname or "").lower()
    except ValueError:
        return "document"
    if not host:
        return "document"
    if host == "arxiv.org":
        return "article"
    if host == "doi.org":
        return "article-journal"
    if host.endswith("youtube.com") or host == "youtu.be":
        return "motion_picture"
    if any(host.endswith(suffix) for suffix in _BLOG_HOST_SUFFIXES):
        return "post-weblog"
    return "webpage"


#: Hosts whose *platform name* is a real container title, and differs from the
#: bare domain in a way worth stating. ``task:0032`` D5.
#:
#: Deliberately short. These are proper names - "arXiv" is not a prettified
#: `arxiv.org`, it is what the preprint server is called and what every citation
#: style expects to see. Everything outside this table falls back to its domain
#: at the facet layer, which is true without needing a table anyone maintains.
_CONTAINER_BY_HOST = {
    "arxiv.org": "arXiv",
    "youtube.com": "YouTube",
    "youtu.be": "YouTube",
    "lesswrong.com": "LessWrong",
    "alignmentforum.org": "AI Alignment Forum",
    "forum.effectivealtruism.org": "EA Forum",
}


def with_www(url: str) -> str | None:
    """The same URL with a ``www.`` host, or ``None`` if it already has one.

    Canonicalization strips ``www.`` (``canonical-url.ts``), which is right:
    almost every host serves both, so keeping the prefix would mint two entries
    for one source and defeat ``task:0021`` D1.

    Almost every host. Measured over this corpus, **seven URLs answer only on
    ``www.``** - the four ``planned-obsolescence.org`` posts (a Substack custom
    domain, which 404s on the bare host), an AP News article, `overcomingbias`,
    and a Carter Center PDF. Stripping it turned working citations into dead
    ones, and because the store's URL is what the bibliography renders as a link,
    a reader clicking those got a 404.

    So identity keeps the stripped form and *reachability* is allowed to differ -
    the same split CSL already draws between ``id`` and ``URL``.
    """
    parts = urlsplit(url)
    if not parts.hostname or parts.hostname.startswith("www."):
        return None
    return urlunsplit((parts.scheme, f"www.{parts.netloc}", parts.path, parts.query, ""))


def infer_container_title(url: str) -> str | None:
    """The container a canonical URL names with certainty, or ``None``.

    The same shape as :func:`infer_csl_type`, and for the same reason: a fact the
    URL states outright, computed in one place so a resolver and the extractor
    cannot disagree about it. A resolver with a *stated* container always wins -
    this only ever fills a blank.
    """
    try:
        host = (urlsplit(url).hostname or "").lower()
    except ValueError:
        return None
    if not host:
        return None
    host = host.removeprefix("www.")
    for suffix, container in _CONTAINER_BY_HOST.items():
        if host == suffix or host.endswith("." + suffix):
            return container
    return None


def fill_container_titles(store: Store) -> tuple[Store, int]:
    """Give every entry whose URL names a container one, without re-fetching.

    ``task:0032`` AC-7. 306 arXiv preprints were resolved before the arXiv
    resolver recorded a container, and ``--redo=arxiv`` would re-fetch all 306
    from a public API to learn a constant we already know. That is both slow and
    rude to someone else's infrastructure for zero information gained.

    Never overwrites: an entry that already states a container keeps it, because
    a resolver read that off the source and this only reads it off the address.
    """
    out: Store = dict(store)
    filled = 0
    for key, entry in out.items():
        item = entry.get("item", {})
        if item.get("container-title"):
            continue
        container = infer_container_title(item.get("URL") or key)
        if container:
            out[key] = {**entry, "item": {**item, "container-title": container}}
            filled += 1
    return out, filled


#: Separators a site puts between a page title and its own name.
#:
#: A hyphen counts **only when it is spaced**. "Deep Blue - IBM" uses one, so it
#: cannot be left out, but a hyphen inside a word is not punctuation between
#: fields: taking a tight one as a separator turned "Beware safety-washing - EA
#: Forum" into "Beware safety" and "reducing s-risks - Center on Long-Term Risk"
#: into "reducing s". Both passed the host proof, because the fragment left over
#: still contained the site's name.
_TITLE_SEPARATOR = re.compile("\\s+-\\s+|\\s*[|\\u2013\\u2014\\u00b7]\\s*")

#: Longest a trailing site name may plausibly be.
_MAX_SUFFIX = 40

#: Shortest a title may be left, and shortest a name may be to match a host.
#: Two characters would let "AI" match any host with those letters in it.
_MIN_TITLE = 3
_MIN_NAME = 3

#: How much longer than the host label a matching site name may run. "Google
#: DeepMind" is the host label plus a vendor prefix; "Play Chess Online - Free
#: Games" is a page title that merely contains "chess".
_NAME_SLACK = 16


def _squash(text: str) -> str:
    """Lowercase alphanumerics only, for comparing a site name with a host."""
    return re.sub(r"[^a-z0-9]", "", text.lower())


def _names_the_host(suffix: str, host: str) -> bool:
    """Whether a trailing fragment is provably this site's own name.

    Two directions, because a host says the same thing two ways: `theaidigest.org`
    contains "AI Digest" outright, while `deepmind.google` is contained *by*
    "Google DeepMind". The length bound is what keeps the second direction from
    firing on any long title that happens to contain the host's label.
    """
    name, whole = _squash(suffix), _squash(host)
    label = _squash(host.split(".")[0])
    if len(name) < _MIN_NAME:
        return False
    if name in whole:
        return True
    return bool(label) and label in name and len(name) <= len(label) + _NAME_SLACK


def site_suffix(title: str, url: str) -> tuple[str, str] | None:
    """``(title without the site name, the site name)``, or ``None``.

    Open Graph titles routinely carry the site name - "Deepfakes Policy |
    ControlAI", "Specification gaming: the flip side of AI ingenuity - Google
    DeepMind" - because that is what a browser tab is supposed to show. A
    bibliography is not a browser tab, and the suffix is not part of the work's
    title. 58 entries in this corpus carry one.

    ``dropRedundantContainer`` in ``bibliography.ts`` already handles the
    mirror-image case, blanking a *container* the title repeats. It cannot help
    here, because these entries have no container at all: the site name is
    sitting in the one field that is not supposed to hold it.

    **The split is only made when it can be proved** against the URL's own host.
    That is the difference between this and the guesswork ``task:0032`` D5
    rejected when it refused to write a domain-to-publisher table: nothing is
    looked up, and a suffix the host does not corroborate is left exactly where
    it is. "Attention Is All You Need - Transformers" on arXiv loses nothing.

    Candidates are tried **longest first**, which is the whole of the difference
    between working and not. A site name may itself contain a separator - "Center
    on Long-Term Risk" - so the rightmost separator is not reliably the right
    one; taking it would leave "…Center on Long" and call "Term Risk" the site.
    Going the other way, `Chess.com - Play Chess Online - Free Games` is a title
    with no site name in it at all, and only the length bound stops the longest
    candidate from claiming to be one.
    """
    title = title.strip()
    try:
        host = (urlsplit(url).hostname or "").lower().removeprefix("www.")
    except ValueError:
        return None
    if not host:
        return None

    candidates: list[tuple[str, str]] = []
    for match in _TITLE_SEPARATOR.finditer(title):
        stem, suffix = title[: match.start()].strip(), title[match.end() :].strip()
        if len(stem) >= _MIN_TITLE and 0 < len(suffix) <= _MAX_SUFFIX:
            candidates.append((stem, suffix))

    for stem, suffix in sorted(candidates, key=lambda pair: -len(pair[1])):
        if _names_the_host(suffix, host):
            return stem, suffix
    return None


def split_site_suffixes(store: Store) -> tuple[Store, int]:
    """Move a site name out of every title that is carrying one.

    Offline, and run beside :func:`fill_container_titles` for the same reason:
    this is a fact the address already states, so re-fetching 56 pages from
    other people's servers to learn it would be slow and rude.

    The name is not discarded - it becomes ``container-title`` where that field
    is empty, which is where it belonged in the first place and which gives the
    source facet a real name instead of a bare domain. An entry that already
    states a container keeps it: a resolver read that off the page.

    **Stripped to convergence, not once**, which is what makes ``extract``
    idempotent (``task:0021`` AC-1). One title in this corpus carries the site
    name twice - "Transcript for … | Lex Fridman Podcast #431 - Lex Fridman" -
    so a single pass left a second one behind, and the *next* run removed it and
    wrote a different file from the same input. The first suffix found is the
    one recorded as the container, because it is the outermost.
    """
    out: Store = dict(store)
    moved = 0
    for key, entry in out.items():
        if entry.get("resolvedBy") == "anchor":
            # An unresolved entry's title is its anchor text, and a citation
            # anchor is not a page title to clean up.
            continue
        item = entry.get("item", {})
        title = item.get("title")
        if not isinstance(title, str):
            continue

        url = item.get("URL") or key
        container = None
        while (split := site_suffix(title, url)) is not None:
            title, suffix = split
            container = container or suffix

        if container is None:
            continue
        updated = {**item, "title": title}
        if not updated.get("container-title"):
            updated["container-title"] = container
        out[key] = {**entry, "item": updated}
        moved += 1
    return out, moved


def entry_from_anchor(key: str, anchor_text: str, parsed: dict[str, str] | None) -> StoreEntry:
    """A minimal entry built from nothing but a canonical URL and its anchor text.

    This is what ``atlas citations extract`` produces before any network call,
    and it is already a usable bibliography entry: 96.8% of anchors in this
    corpus carry an author and a year. Resolution improves entries; it is not a
    precondition for having them.
    """
    item: CslItem = {"id": key, "type": infer_csl_type(key), "URL": key}
    if parsed:
        item["author"] = [literal_name(parsed["author"])]
        item["issued"] = year_to_csl_date(parsed["year"])
        item["title"] = anchor_text
        item["note"] = "Unresolved: title and author taken from the citation anchor text."
    else:
        item["title"] = anchor_text or key
        item["note"] = "Unresolved: no author-year could be parsed from the anchor text."
    return {"item": item, "resolvedBy": "anchor", "anchors": [anchor_text] if anchor_text else []}


def merge_entry(existing: StoreEntry, incoming: StoreEntry) -> StoreEntry:
    """Merge a newly-extracted entry into an existing one.

    Extraction must never overwrite resolved metadata - ``atlas citations
    extract`` runs often and resolution is expensive, so a re-extraction that
    clobbered resolver output would throw away the work ``task:0027`` exists to
    do. Only the observed anchor list grows.
    """
    anchors = sorted(set(existing.get("anchors", [])) | set(incoming.get("anchors", [])))
    if existing.get("resolvedBy") != "anchor":
        return {**existing, "anchors": anchors}

    # Re-derive the anchor content - the prose may have been edited - but keep
    # what the last resolve attempt learned about the *address*, which no edit to
    # a sentence can change. Without this, `extract` silently wiped every
    # `unreachable` marker, and since `extract` runs immediately before `report`,
    # the dead-link section (task:0032 AC-6) would have been permanently empty.
    merged: StoreEntry = {**incoming, "anchors": anchors}
    if existing.get("unreachable"):
        merged["unreachable"] = existing["unreachable"]
    return merged


def upsert_entries(store: Store, entries: list[tuple[str, StoreEntry]]) -> Store:
    """Fold extracted citations into a store, preserving anything already resolved."""
    out: Store = dict(store)
    for key, entry in entries:
        out[key] = merge_entry(out[key], entry) if key in out else entry
    return out


def serialize_store(store: Store) -> str:
    """Serialize a store to CSL-YAML. Keys are sorted so diffs stay reviewable."""
    ordered = {key: store[key] for key in sorted(store)}
    buf = io.StringIO()
    _yaml().dump(ordered, buf)
    return _FILE_HEADER + buf.getvalue()


def parse_store(text: str) -> Store:
    """Parse CSL-YAML back into a store. An empty or comment-only file is empty."""
    parsed = _yaml().load(text)
    if not isinstance(parsed, dict):
        return {}
    return _plain(parsed)


def _plain(value: Any) -> Any:
    """Strip ruamel's round-trip wrapper types back to plain Python containers.

    Without this, comparisons and ``json.dumps`` see ``CommentedMap`` /
    ``CommentedSeq`` / ``ScalarString`` subclasses. They behave like their bases
    almost everywhere, which is exactly what makes the leak hard to notice until
    something equality-sensitive fails.
    """
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_plain(v) for v in value]
    if isinstance(value, str):
        return str(value)
    return value


def to_csl_json(store: Store) -> list[CslItem]:
    """CSL-JSON: the compiled form, an array of items as the specification defines."""
    return [store[key]["item"] for key in sorted(store)]
